### ISSUE TITLE
Generate and improve our ideas

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#1]
Let's generate and explain some ideas from us here. :clap:

> Antara hari ini atau besok. Kita generate ide sebanyak-banyaknya ya. Terus kita eliminasikan dan diskusikan mana yang mau kita kerjain.

cc: @muhpatr @rutheodora @ekkyvalent

**Comment by mhaidarhanif** [comment]
@rutheodora:

> Btw berhubung waktu itu ibunya bilang usernya boleh yg kita sendiri , gw jabarin yak kalo usernya GW, butuhnya apa
> Aplikasi pendataan komik gw tuh apa aja wakakak
> Jdi semacam perluasan dari notes gitu deh intinya nyimpen judul komik gw, volume/satuan, rak nya dimana dll, kayak komputer diperpus2 gitu hohoho
> Trus.. kalender period (okeh itu udah ada wkwk)
> Itu tuh...kalo kalian tau aplikasi monefy, gw pingin ada aplikasi foodfy (??) jdi kayak diary kecil gitu yg isinya gw makan apa aja hari ini, trus berapa duit yg keluar buat makan, dll
> Hmm kalender yg lo bilang dulu kyy, yg kalo mau dapet anak cewe tggl kapan, anak cowo tggl berapa wakakakak
> Udah dri gw itu aja dulu yg pribadi, tpi kalo yg kayak ide ekky gw blum dpt yg emang lgi dibutuhin sekarang tuh apa wakakak
> Yg superhero kayak quiz2 di fb gitu patz?
> Jir ava kita neko atsumeeeeee huwaaaa

**Comment by mhaidarhanif** [comment]
@muhpatr:

> setuju sih. simpel tp terarah.
> *cie
> gue butuh aplikasi yg bs prediksi gue jadi apa di masa depan. atau siapa superhero yg cocok dgn kepribadian gue. dll gitu
> kalo ide gue yg beneran... gue diminta bkin aplikasi gitu sm kaka gue, jd dia kan punya usaha sewa sepeda di puncak, nah operator di sana di hapenya diinstall aplikasi buat confirm speda yg dipinjam sm yg udh balik. gunanya si kaka gue biar tau aja status peminjaman sepedanya udh brp dlsb. ini si project gue sendiri, kali aja mau sekalian gitu.
> kasih contohnya yak dar

**Comment by mhaidarhanif** [comment]
@mhaidarh:

> @rutheodora: hahah Pas banget macam Calibre atau Koha
> Hmm oke oke di-list ya di dalam suatu tulisan yang komplit dengan penjelasan (bukan conversational). Bisa juga edit di README, daftar ide yang kita punya. Sekaligus dengan Project & User Definition. Lebih optimal lagi, tiap ide dikasi tau proyeksi berapa lama waktu pengerjaan.
> Kalo diary track expense, banyak juga referensi.
> 
> @ekkyvalent: Ekky mau KB.
> Ohya, kalo ada referensi aplikasi sejenis juga lebih baik.
> 
> @muhpatr: Bisa, bisa. Renting App. Coba dijabarkan kebutuhan user lebih lanjut di dokumen ya.
> Sebaiknya nanti yang kita pilih ide yang paling user butuhkan, make sense, dan waktu pengerjaannya bisa kurang dari 60 hari (buat jaga-jaga bahkan kalo bisa kurang dari 30 hari).
> Oke berarti sekalianin masing-masing kita ceritain kebutuhan pengguna.
> (Mendingan si bukan user diagram, tapi ceritain aja, terus dijabarkan poin2 penting yang harus ada)
> Gue juga lagi coba generate banyak dulu.

**Comment by mhaidarhanif** [comment]
Our ideas can be discussed here or in WhatsApp chat, then poured into [IDEAS](https://github.com/gunadarma-academy/asde-michi/blob/master/IDEAS.md).

Oke jadi kalo ide gue yang pertama ini mirip Rate My Professors atau Rate My Teachers, tapi lebih buat audiens lokal kayak kita-kita. Fokus utamanya buat anak kuliah tahun/sarjana apapun, buat ngasi _rating_ dan _comment_ yang lebih melokal, tentang kehidupan kampus.  

Kenapa ide gue ini karena banyak masalah kampus yang seringkali cuma ditaro atau diomongin di Twitter, Facebook, dll terus numpuk dan ga terstruktur. Kebanyakan dosen juga kan ga tau. Jadi kalo ngumpulin opini kampus (ya minimal satu kampus yang kita masih lagi ada di dalemnya) di satu tempat, bakal bisa lebih efektif dan efisien buat mewujudkan kehidupan kampus yang lebih baik.

**Comment by mhaidarhanif** [comment]
@ekkyvalent:  

> Gue lagi nuangin ide community-driven transporation helper ke git

**Comment by mhaidarhanif** [comment]
> Sip sip
> Besok diusahakan jam 10an ya udah sampai. Kalo gue si jam 6-7 pagi. Jadi kita ada waktu untuk diskusi yang seger. Termasuk nentuin yang bakal kita kerjain, jika sempat.

**Comment by ekkyvalent** [comment]
Jadi di sini bisa buat chatting juga.

Keren sih.

**Comment by muhpatr** [comment]
Dar, lo ngubah PP github gue ya -_-

**Comment by mhaidarhanif** [comment]
@ekkyvalent: Iya bahkan ini _real time_ juga. Serta ada _formatting_ dan _edit_ jadi enak bacanya.

@muhpatr: hah Ga mungkin pat gue kan ga login. Kemaren incognito terus langsung ditutup. Mungkin lo lelah.

**Comment by muhpatr** [comment]
@mhaidarh: oh berarti si junior, karna gue login di pcnya :') btw ini agak ganggu email sih dar, masuk ke email mulu soalnya.

**Comment by mhaidarhanif** [comment]
@muhpatr: Bisa dinonaktifkan di settings pat.

https://github.com/settings/notifications

Kalau mau lebih efektif lagi, tiap notifikasi di Gmail pindahin ke tab Forums.

**Comment by mhaidarhanif** [comment]
Btw tips _commit message_ sebagai pengingat kita:

> Sebisa mungkin di heading-nya seperti judul biasa jika muat kurang dari 80 karakter. Barulah kalau ga muat di paragrafnya.

Misalnya:

> Add Haidar's idea about campus quality
> Add Ruth's idea about book list organizer
> Add Ekky's idea about transportation helper
> Add Patr's idea about bike rental

**Comment by ekkyvalent** [comment]
@mhaidarh seumur-umur baru aktifin tab forum di Gmail. Haha oke deh thanks for the input.

**Comment by mhaidarhanif** [comment]
@ekkyvalent: Yo sip. Kalo gue si pake email yang beda juga (git@mhaidarhanif.com) biar kepisah.

**Comment by muhpatr** [comment]
Jadi pengen punya domain sendiri :')

**Comment by mhaidarhanif** [comment]
@muhpatr:
Kalau mau paling hemat sekarang `*.xyz` cuma kisaran $2, bisa pake PayPal sendiri atau temen. [Registrar terbaik sekarang di muka bumi ini: https://uniregistry.com]

Tapi kalo email sebaiknya pake SaaS yang gratis (Zoho: https://zoho.com/mail) atau bayar dikit (Google Apps: https://apps.google.com).

**Comment by ekkyvalent** [comment]
@muhpatr emailnya **patria@michi.com**?

**Comment by mhaidarhanif** [comment]
@ekkyvalent Silakan Anda bisa menutup _issue_ ini dengan komentar atau _commit_ README.

**[TIPS]** Menutup issue dengan _commit_:

> Put all the intro details in README, resolve #1

https://help.github.com/articles/closing-issues-via-commit-messages

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi 

> **Besok**
> 
> Gue ngurusin backend dan datanya dengan Node.js dan MongoDB, nyiapin repo `app` hingga siap pakai bahkan deploy ke server
> 
> Ekky ngurusin website mockup dengan Semantic UI, ada di https://github.com/gunadarma-academy/asde-michi-web
> 
> Uthe ngurusin branding style dan logo, naro di `design/logo`
> 
> Patria karena ada kerjaan lain, liat dan baca2 lagi aja dulu: https://waffle.io/gunadarma-academy/asde-michi, juga terutama issue repo lo sendiri: https://github.com/muhpatr/node-contact-app/issues

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi 
Some inspirational and practical advice about building or developing product:
- [Talking to Humans: Success starts with understanding your customers, by Giff Constable](http://talkingtohumans.com) (Free Ebook)
- http://www.talkingtohumans.com/cartoons
- http://giffconstable.com/2016/03/getting-tactical-product-team-working-agreements
- http://giffconstable.com/2016/03/good-vs-bad-product-management
- http://giffconstable.com/2016/03/how-engineering-leads-can-work-well-with-product-management-leads
- https://blog.intercom.io/unflattening-design
- https://mariocardinal.wordpress.com/2015/06/22/minimum-lovable-product
- https://mariocardinal.wordpress.com/2015/07/05/success-is-all-about-structure
- https://mariocardinal.wordpress.com/2015/08/29/building-the-product-right

![Talking to Humans cartoon](http://www.talkingtohumans.com/img/NYU.lowres.ifiwere.jpg)
![Product Management Graph](http://giffconstable.com/wp-content/uploads/Screen-Shot-2016-03-10-at-8.29.23-AM-1400x1081.png)
