### ISSUE TITLE
Determine templates for master test plan

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#32]
Quick SOW: Determine templates for master test plan
# TUGAS & UJIAN MATA KULIAH TESTING DAN IMPLEMENTASI SISTEM
1. Pembuatan dokumen "Master Test Plan berdasarkan "User Requirement" masing-masing kelompok (gunakan template).
2. Pembuatan Dokumen "Skenario Test" berdasarkan "Master Test Plan" yang dibuat (Metode tidak hanya black box, jika tidak sempat, acceptance test boleh diabaikan dulu).
3. Melakukan test berdasarkan "Skenario Test" yang dibuat.
## DISKUSI
1. Penentuan template dari dokumen master test plan
2. Membuat folder khusus untuk dokumen testing (2 buah dokumen: Skenario Test & Master Test Plan)

Contoh dokumen master test plan:
- http://www.it.northwestern.edu/bin/docs/project-framework/Master_Test_Plan_v061111.docx
- http://www.tmap.net/sites/default/files/Template_Master_Test_Plan_TMap_NEXT_v2_1%20(1).doc

Refer to this issue: https://github.com/gunadarma-academy/asde-michi/issues/2

**Comment by rutheodora** [comment]
summon: @mhaidarh @muhpatr @ekkyvalent

**Comment by rutheodora** [comment]
referensi untuk testing: Design Sprint Methods

https://developers.google.com/design-sprint/downloads/DesignSprintMethods.pdf

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi Please see the new created repo for this particular purpose: https://github.com/gunadarma-academy/asde-michi-test

**Comment by mhaidarhanif** [comment]
@rutheodora @muhpatr @ekkyvalent Oke jadi mau pilih yang berbasis dari northwestern.edu atau tmap.net?

Ntar ngerjainnya di https://github.com/gunadarma-academy/asde-michi-test pake Markdown ya.

**Comment by rutheodora** [comment]
@mhaidarh eehh itu cuma contoh yang kita temuin tadi dar, kalo ada template lain yang lebih cocok kita belum cari2 lgi td

**Comment by mhaidarhanif** [comment]
@rutheodora Sebenernya gapapa kita ngadopsi konten dokumen itu. Bahkan bisa digabung sama https://www.uxpin.com/usability-test-kit.html

Karena metode Design Sprint fleksibel tentang bagaimana kita nulis dokumen laporannya. Yang penting esensinya terlaksana.

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi Kebetulan yang dari Northwestern lebih pendek dan intuitif untuk dipahami. Langsung pilih ini aja ya.

**Comment by mhaidarhanif** [comment]
@rutheodora Cek untuk clone/pull https://github.com/gunadarma-academy/asde-michi-test ya the.

**Comment by mhaidarhanif** [comment]
@gunadarma-academy/michi 
Karena ini prioritasnya agak rendah, baru bisa beneran dijalanin dan mungkin saja juga bikin SOW baru setelah mockup dan API jadi, maka pelajari dulu aja hal-hal yang mau dites. Berdasarkan template master test plan dan design sprint. :+1: 

References:
- http://www.gv.com/sprint
- https://developers.google.com/design-sprint/downloads/DesignSprintMethods.pdf
- https://twitter.com/GVDesignTeam/status/710650467085328385
- https://www.uxpin.com/usability-test-kit.html
- https://www.youtube.com/watch?v=QwJwemOX37w
- https://www.youtube.com/watch?v=SEm7sXfbqfQ
