### ISSUE TITLE
Complete Brand Specification document

### ISSUE THREAD

**Issue by rutheodora** [gunadarma-academy/asde-michi#33]
- Kind: Statement of Work
- Title: Complete Brand Specification document
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-03-29
- Version: 0.2
# SOW
## Overview

Describe the branding of Arlin 
## Tasks
- [x] Describe Arlin
- [x] Describe its shape (from logo and template web)
- [x] Describe color/the psychology of color and typography (from logo and the web)
## Deliverables

will be done the day after tomorrow (Thursday, March 31), the result is in BRAND-SPEC.markdown file
## Dependencies

Issue https://github.com/gunadarma-academy/asde-michi/issues/25 needs to be done

**Comment by rutheodora** [comment]
@ekkyvalent : kalo ada bahasa indonesia, mungkin bisa di translate oleh Anda.
ohohohohohohohohohohohohohohohohohohohohohohohohohoohohohohoho

**Comment by mhaidarhanif** [comment]
@rutheodora Ntar kalo ini udah selesai, lanjut untuk cek https://github.com/gunadarma-academy/asde-michi/issues/32 (master test plan) ya the.

Atau bisa lihat langsung di https://github.com/gunadarma-academy/asde-michi-test

**Comment by rutheodora** [comment]
@mhaidarh: ini gw udah jabarin brandingnya di https://github.com/gunadarma-academy/asde-michi/blob/master/design/brand/BRAND-SPEC.markdown maaf nyampur bahasa inggris indo, ini belum final, finalnya bersamaan sama mockup selesai tpi intinya point2 yang mau gw bahas udah dar.
mohon dikoreksi, maaf gw kalo ada yang ga sesuai :"" gw besok baru buka laptop lagi dar, badan gw ga enak tiba2 , lo juga jaga kesehatan lo yaaaa

**Comment by rutheodora** [comment]
@ekkyvalent : kyy, dicek yaa ky, ini fontnya nambah satu, yang proxima itu, kalo ada tambahan font lain yang mau lo pake karena keliatannya cocok pas nyoba2, wa aja, nnti gw tambahin di dokumentasi

trus kalo bisa lo tambahanin di dokumentasi yang bagian "What is unique about your Arlin? Why should people choose your Arlin? " gw mati ide https://github.com/gunadarma-academy/asde-michi/blob/master/design/brand/BRAND-SPEC.markdown

**Comment by mhaidarhanif** [comment]
@rutheodora Sip sip. Gapapa yang penting progress.

**Comment by rutheodora** [comment]
HELP ME TO TRANSLATE THE BRAND SPEC DOCUMENT @muhpatr ohohoho

**Comment by ekkyvalent** [comment]
@rutheodora I've translated the brand spec document, please look up to it.
