### ISSUE TITLE
Data entry for Arlin initial content (Part A)

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#42]
- Kind: Statement of Work
- Title: Data entry for Arlin initial content (Part A)
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-04-13
- Version: 0.1
# SOW
## Overview

Data entry for fill in the initial content for Arlin website. I will work with @rutheodora to do this task.
## Tasks
- [x] Determining regions
- [x] Data entry based on the area of:
  - [x] North Jakarta
  - [x] West Jakarta
  - [x] Depok
  - [x] Bogor
  - [x] Tangerang
  - [x] Bekasi
- [x] Move the data into the website
## Deliverables

Will be done before 24th April, the result can be seen on the Arlin website
## Dependencies

Deployment (#35) needs to be done

**Comment by mhaidarhanif** [comment]
@muhpatr 
[mongodump-bsondump-20160418_111024.zip](https://github.com/gunadarma-academy/asde-michi/files/223613/mongodump-bsondump-20160418_111024.zip)

**Comment by mhaidarhanif** [comment]
@muhpatr @rutheodora Untuk collection `preload-data`, formatnya diganti saja jadi lebih minimal layaknya parameter dengan urutan:

```
"author", "title", "description", "categories", "answers"
```

jadi seperti ini aja tiap file `question-x.json`:

```
"mhaidarh", "Cara paling cepat keliling Jabodetabek?", "Saya mau jalan-jalan keliling Jabodetabek dengan cepat. Kira-kira bisa ga?", [ "jakarta", "bogor", "depok", "tangerang", "bekasi" ], [ "Bisa aja kalo lagi pada lebaran" ]
```

Gue udah update question 1 & 2 buat contoh di `asde-michi-test` sehubungan ini.

**Comment by muhpatr** [comment]
@mhaidarh di situ ga ada answer author. dan kayaknya mending pakai format json sebelumnya aja, lebih informatif dan rapi. cc: @rutheodora

**Comment by mhaidarhanif** [comment]
@muhpatr Ohiya juga. 
Iya si pat, tapi untuk masukin ke database-nya ternyata lebih cepet format minimal, kayak parameter.

**Comment by mhaidarhanif** [comment]
Kalo ada answer author, jadi gini:

jadi seperti ini aja tiap file `question-x.json`:

```
"mhaidarh", "Cara paling cepat keliling Jabodetabek?", "Saya mau jalan-jalan keliling Jabodetabek dengan cepat. Kira-kira bisa ga?", [ "jakarta", "bogor", "depok", "tangerang", "bekasi" ], [ {"muhpatr", "Bisa aja kalo lagi pada lebaran"}, { "rutheodora", "Naik helikopter palingan" } ]
```

**Comment by mhaidarhanif** [comment]
Hmm oke kalo rada bingung _fallback_ ke format JSON yang normal. Even though it's a lot of work.
