### ISSUE TITLE
Create and spread online questionnaire (Part A)

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#44]
- Kind: Statement of Work
- Title: Create and spread online questionnaire
- Author: Ruth Theodora
- Affiliation: Michi
- Date: 2016-04-13
- Version: 0.1
# SOW
## Overview

I and @muhpatr will distribute the questionnaires for doing the User Acceptance Test. We will distribute them to Jabodetabek people.
## Tasks
- [x] Creating the online questionnaires via Typeform
- [x] Spread the questionnaires to people in:
  - [x] East Jakarta 
  - [x] Central Jakarta
  - [x] South Jakarta 
  - [x] West Jakarta
  - [x] Central Jakarta 
  - [x] Tangerang
  - [x] Depok
  - [x] Bogor
  - [x] Bekasi/Bandung
## Deliverables

After the questionnaires have been spread, we will analyze the result and upload the result to this repo.
## Dependencies

Issue #40, #41, and #35 must be done first

**Comment by mhaidarh** [comment]
@muhpatr @rutheodora Please be noticed :warning: Finish #42 and #43 first, then you can proceed to spread about the app and its survey.

**Comment by muhpatr** [comment]
The online form can be accessed via http://bit.ly/arlinmichi
@rutheodora @mhaidarh

**Comment by muhpatr** [comment]
The online form has been reached 50 respondents.
