### ISSUE TITLE
Create and spread online questionnaire (Part B)

### ISSUE THREAD

**Issue by muhpatr** [gunadarma-academy/asde-michi#45]
- Kind: Statement of Work
- Title: Create and spread online questionnaire
- Author: Muhammad Patria
- Affiliation: Michi
- Date: 2016-04-13
- Version: 0.1
# SOW
## Overview

I and @rutheodora will distribute the questionnaires for doing the User Acceptance Test. We will distribute them to Jabodetabek people.
## Tasks
- [x] Creating the online questionnaires via Typeform
- [x] Spread the questionnaires to people in:
  - [x] East Jakarta 
  - [x] Central Jakarta
  - [x] South Jakarta 
  - [x] West Jakarta
  - [x] Central Jakarta 
  - [x] Tangerang
  - [x] Depok
  - [x] Bogor
  - [x] Bekasi/Bandung
## Deliverables

After the questionnaires have been spread, we will analyze the result and upload the result to this repo.
## Dependencies

Issue #40, #41, and #35 must be done first

**Comment by mhaidarh** [comment]
@muhpatr @rutheodora Please be noticed :warning: Finish #42 and #43 first, then you can proceed to spread about the app and its survey.

**Comment by muhpatr** [comment]
The online form can be accessed via http://bit.ly/arlinmichi
@rutheodora @mhaidarh

**Comment by mhaidarhanif** [comment]
@muhpatr 
![image](https://images.unsplash.com/photo-1414115880398-afebc3d95efc)

**Comment by muhpatr** [comment]
@mhaidarh 
![arlin-icon](https://cloud.githubusercontent.com/assets/4652284/14634140/d4a719aa-064a-11e6-8441-74480083b02c.png)

**Comment by muhpatr** [comment]
The online form has been reached 50 respondents.
