### ISSUE TITLE
Group deliverables report of each SOW

### ISSUE THREAD

**Issue by mhaidarhanif** [gunadarma-academy/asde-michi#53]
- Kind: Statement of Work
- Title: Group deliverables report of each SOW
- Author: Patria and Ruth
- Affiliation: Michi
- Date: 2016-04-21
- Version: 0.1
# SOW
## Overview

Create the document for all SOWs as the report.
## Tasks
- [x] Pick the finished milestones.
- [x] Create the document to our repo.
## Deliverables

The document will be pushed to our repo with the name `DELIVERABLES.markdown` in the `report` folder.
## Dependencies

The finished document depends on the finished milestones.

**Comment by mhaidarhanif** [comment]
@muhpatr 
Dengan bantuan burndown view dari ZenHub, dalam `DELIVERABLES.markdown` di folder `reports`, strukturnya seperti ini:

```
# Arlin by Michi Report: Deliverables

## <Milestone Name>

![<milestonename>](<milestonename-burndown.png>)

### <Number>: <Issue Name>
<deliverables description>

### <Number>: Issue Name>
<deliverables description>

---

## <Milestone Name>

![<milestonename>](<milestonename-burndown.png>)

### <Number>: <Issue Name>
<deliverables description>

### <Number>: Issue Name>
<deliverables description>

---

## <Milestone Name>

![<milestonename>](<milestonename-burndown.png>)

### <Number>: <Issue Name>
<deliverables description>

### <Number>: Issue Name>
<deliverables description>

...

```

Yang baru bisa dikerjain untuk milestone yang udah selesai, ada 5 milestone & burndown.

**Comment by muhpatr** [comment]
@mhaidarh dar, kasih urutan dong milestone mana yang lebih dulu dikerjain (urutan milestonenya)

**Comment by mhaidarhanif** [comment]
@muhpatr 

```
1. Project Management Setup
2. Product Roadmap for Arlin v1
3. Learning the Basics
4. Initial UI/UX Design
5. Initial Technology Stack
6. User Generated Content
7. User Acceptance Testing
8. Product Roadmap for Arlin v2
9. Application Testing

One Epic: Product Launch of Arlin v2 (things that included for exam)
```

**Comment by muhpatr** [comment]
@mhaidarh thanks :+1:

**Comment by mhaidarhanif** [comment]
@muhpatr @rutheodora @ekkyvalent  Untuk lihat EPIC, cek2 ke https://github.com/gunadarma-academy/asde-michi/issues/50

**Comment by mhaidarhanif** [comment]
EPIC-nya cuma satu, mengandung Product Launch of Arlin v2, isinya terdapat 13 issues. Sudah 3 issues selesai. Sisanya 10 issues adalah dari milestone:
1. User Acceptance Testing
2. Product Roadmap for Arlin v2
3. Application Testing

**Comment by muhpatr** [comment]
![1-project-management-setup](https://cloud.githubusercontent.com/assets/4652284/14812230/78597342-0bc6-11e6-9be6-759ea3dd52e8.png)

![2-product-roadmap-for-arlin-v1](https://cloud.githubusercontent.com/assets/4652284/14812321/ea28f8bc-0bc6-11e6-8779-2c97b45e76ed.png)

![3-learning-the-basics](https://cloud.githubusercontent.com/assets/4652284/14812344/fed8bbda-0bc6-11e6-930d-6b79d353e564.png)

![4-initial-ui-ux-design](https://cloud.githubusercontent.com/assets/4652284/14812343/fed8560e-0bc6-11e6-99ec-fc9beaa45625.png)

![5-initial-technology-stack](https://cloud.githubusercontent.com/assets/4652284/14812341/fed50ecc-0bc6-11e6-9d99-4f7ec7433c73.png)

![6-user-generated-content](https://cloud.githubusercontent.com/assets/4652284/14812345/fed8f596-0bc6-11e6-9599-de310a4e567e.png)

![7-user-acceptance-testing](https://cloud.githubusercontent.com/assets/4652284/14812601/0113e4dc-0bc8-11e6-9a98-be5082cb8f06.png)

**Comment by muhpatr** [comment]
@mhaidarh Learning the basic milestone kok ga ada di burndown?

**Comment by mhaidarhanif** [comment]
@muhpatr Hmm iya juga. Bentar coba dicek.

**Comment by mhaidarhanif** [comment]
@muhpatr Sekarang udah muncul pat: https://github.com/gunadarma-academy/asde-michi/milestones#burndown?milestoneId=4

**Comment by muhpatr** [comment]
@mhaidarh sama ada bbrp SOW yg kyknya ga cocok ditaroh di suatu milestone. misal, issue 36 ke atas kyknya kurang cocok ditaruh di Product Roadmap for Arlin v1, karna jaraknya jauh bgt sm issue sblmnya.

**Comment by mhaidarhanif** [comment]
Lah iya itu mestinya masuk ke Product Roadmap v2

**Comment by mhaidarhanif** [comment]
Iya #36 sampai #41 mestinya masuk milestone v2. Lo pindahin deh.

**Comment by muhpatr** [comment]
@mhaidarh sekalian cek milestone lain deh coba. sama bingung nentuin start sm due date nya. bbrp ada yg kyknya kejauhan, ada yg salah satu issue jd ga muncul, kyk #32 di Project Management Setup (btw, ini Project Management Setup kok jd ilang)

**Comment by mhaidarhanif** [comment]
@muhpatr Kalo ada yang ga muncul, coba reopen terus close milestone itu. Kayaknya bug dari ZenHub.

**Comment by mhaidarhanif** [comment]
@muhpatr Untuk tanggal, dikira-kira aja pat kalo mau dimodifikasi.

**Comment by mhaidarhanif** [comment]
Ini udah muncul lagi yang PM Setup: https://github.com/gunadarma-academy/asde-michi/issues/53#burndown?milestoneId=3

Tapi pasti ada milestone lain yang ilang, lo reopen aja

**Comment by muhpatr** [comment]
@mhaidarh terus yg #32 ditaruh dmn? kyknya kurang cocok klo di setup, soalnya jauh range tanggalnya

**Comment by mhaidarhanif** [comment]
Memang si, tapi kan itu sudah selesai, sedangkan App Testing dan UAT milestone belum. Paling alternatif taro Product Roadmap for Arlin v1 atau Product Roadmap for Arlin v2. Gapapa sebenernya agak kejauhan tanggal, soalnya range penggunaannya termasuk lebar.

Yang penting lo udah ambil semua screenshot dulu ya.

**Comment by mhaidarhanif** [comment]
#32 jadi tetap di Setup
